<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SkMafDemo.Core\SkMafDemo.Core.csproj" />
    <ProjectReference Include="..\SkMafDemo.SemanticKernel\SkMafDemo.SemanticKernel.csproj" />
    <ProjectReference Include="..\SkMafDemo.AgentFramework\SkMafDemo.AgentFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.6.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="OllamaSharp" Version="5.4.25" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>skmafdemo-58b1f0f8-ea83-4f80-a31a-7c8c4a8b6a1e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
